import { createContext } from "react";

const data = 
  {
    vehicle1: [
      {
        id:1,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:2,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:3,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:4,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:5,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:6,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:7,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
    ],
    vehicle2: [
      {
        id:8,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:9,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:10,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:11,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:12,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:13,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
      {
        id:14,
        startTime: "May 26,5:18 pm",
        duration: "24 min",
        maxSpeed: "91 kmph",
        avgSpeed: "54 kmph",
        startingVoltage: "70.04 V",
        endingVoltage: "69.42 V",
        distance: "5.45 km",
        driverScore: "98.5",
      },
    ],
    vehicle3: [
        {
          id:15,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:16,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:17,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:18,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:19,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:20,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:21,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
      vehicle4: [
        {
          id:22,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:23,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:24,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:25,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:26,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:27,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:28,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
      vehicle5: [
        {
          id:29,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:30,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:31,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:32,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:33,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:34,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:35,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
      vehicle6: [
        {
          id:36,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:37,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:38,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:39,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:40,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:41,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:42,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
      vehicle7: [
        {
          id:43,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:44,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:45,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:46,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:47,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:48,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:49,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
      vehicle8: [
        {
          id:50,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:51,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:52,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:53,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:54,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:55,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
        {
          id:56,
          startTime: "May 26,5:18 pm",
          duration: "24 min",
          maxSpeed: "91 kmph",
          avgSpeed: "54 kmph",
          startingVoltage: "70.04 V",
          endingVoltage: "69.42 V",
          distance: "5.45 km",
          driverScore: "98.5",
        },
      ],
  }

console.log(data, "context");
console.log(data.vehicle1, "context");
console.log(data.vehicle1[0], "context");
console.log(data.vehicle1[0].id, "context");
const context = createContext(data);

export default context;
